# .readthedocs.yaml
version: 2

python:
  version: "3.13"
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py  # root level conf.py

build:
  image: latest
  os: ubuntu-22.04
  tools:
    python: "3.13"  # string, not float
