# .readthedocs.yaml
version: 2

# Python environment
python:
  version: 3.13
  install:
    - requirements: requirements.txt

# Sphinx configuration
sphinx:
  configuration: conf.py

# Build configuration
build:
  image: latest
  os: ubuntu-22.04
  tools: python  # this is required by RTD
  commands:
    - pip install -r requirements.txt  # optional if not in 'install'
    - sphinx-build -b html docs/ build/html
