# .readthedocs.yaml
version: 2

# Python environment
python:
  version: 3.13
  install:
    - requirements: requirements.txt

# Sphinx configuration
sphinx:
  configuration: conf.py  # root level

# Build settings
build:
  image: latest
  os: ubuntu-22.04
  tools:
    python: 3.13  # dictionary format required by RTD
