# .readthedocs.yaml
version: 2

# Python environment
python:
  version: 3.13
  install:
    - requirements: requirements.txt

# Sphinx configuration
sphinx:
  configuration: conf.py

# Build configuration
build:
  image: latest
  os: ubuntu-22.04
  tools:
    sphinx: latest  # required by RTD to know how to build

# Documentation root
docs_dir: .
